# Generated by Django 4.2.2 on 2023-09-19 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_expense_date_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categoryBudget', to='budget.category'),
            preserve_default=False,
        ),
    ]
