# Generated by Django 4.2.2 on 2023-09-28 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_expense_frecuency_alter_expense_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sum', to='budget.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_sum', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
