# Generated by Django 4.2.2 on 2023-09-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_expensesum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseSum',
        ),
    ]
